### ISSUE TITLE
Remove bullet from top level headings

### ISSUE THREAD

**Issue by dcoales** [ruivieira/obsidian-plugin-logseq#1]
LogSeq seems to put a bullet in front of everything - including headings.  This means that headings don't display correctly in Obsidian in edit mode - although they do appear to show as headings in preview mode.  Is there anything that can be done to make the headings appear correctly in Obsidian edit mode.  I would even be happy if the plugin just removed the bullet point from headings that were not indented.  LogSeq will still display these correctly but will then add the bullet back sometimes depending on the edits that you make.

Alternatively - just adding a class to the HTML wherever you find a line that starts with whitespace followed by a dash followed by any number of #'s -  so that I could add my own styling - would also do the trick.

**Comment by ruivieira** [comment]
Hi @dcoales 

I would much rather use the second option (styling the edit view). I think it's important for the plugin to not change the actual source to avoid any kind of future problems in case LogSeq changes the Markdown format.

I'll see what's possible to be done.

**Comment by dcoales** [comment]
You're right of course.  Changing the source would be a bad idea.  
If you could simply wrap the #'s in a span with the classes "cm-formatting", "cm-formatting-header" and "cm-formatting-header-n" (where n is the header level) and then wrap the text after the #'s in a span with the classes "cm-header" and "cm-header-n" then it should work with most standard themes I think.

Alternatively you could replace the cm- part with your own prefix.

**Comment by dcoales** [comment]
I've also noticed that for some reason LogSeq uses ^^ for highlighting rather than the more common ==.  I'm going to post something on the LogSeq forum asking if == could also be supported but it would be nice if you could somehow make ^^ supported in Obsidian :-)

**Comment by ruivieira** [comment]
@dcoales Headings should work now. Could you please open an issue for the `^^` highlight? Thanks.

**Comment by dcoales** [comment]
Will do.  I haven't actually installed the plugin yet and couldn't find it in the community plugins list.  Should I find it there or have you not yet submitted it.

**Comment by ruivieira** [comment]
It's submitted, but waiting review (https://github.com/obsidianmd/obsidian-releases/pull/367). I'm afraid it will have to be from source until it's approved.

**Comment by dcoales** [comment]
Okay thanks.

**Comment by dcoales** [comment]
Thanks very much for the update.  So that I can style it to look nicer in edit mode would it be possible to split the #'s from the text like the standard renderer does ?  The #'s are usually wrapped in  "cm-formatting", "cm-formatting-header" and "cm-formatting-header-n" classes and the text in the "cm-header" and "cm-header-n".   That way I can style the cm-formatting-header class to hide the #'s in edit mode until you click on the line.
